// PobTools atlas-tree Traditional-Chinese display layer.
//
// Reads the bilingual node mapping (Data/atlas_tree_zh.json, generated by the
// updater / tools/gen_atlas_zh.py) and answers name / stat-line lookups for the
// planner UI. Pure data, no network, no GL; every lookup falls back to the
// English input, so a missing or stale file simply shows English text.
#pragma once

#include <string>
#include <unordered_map>

class AtlasI18n {
public:
	// Loads Data/atlas_tree_zh.json under exeDir; safe to call again to reload.
	// Returns false (and clears the tables) when the file is missing/invalid.
	bool Load(const std::wstring& exeDir);
	bool loaded() const { return loaded_; }

	// id = GGG skill hash (AtlasNode.id). Falls back to en when untranslated.
	const std::string& NodeName(int id, const std::string& en) const;

	// Whole-stat-line lookup; aggregation keys stay English, display flips here.
	const std::string& StatLine(const std::string& en) const;

	// e.g. "3.28.0 / repoe 3.28.0.15" for the toolbar tooltip.
	const std::string& VersionNote() const { return note_; }

private:
	std::unordered_map<int, std::string> nameById_;
	std::unordered_map<std::string, std::string> statByEn_;
	std::string note_;
	bool loaded_ = false;
};
