// PobTools atlas planner data model: the condensed PoE1 atlas passive tree
// (generated by tools/gen_atlas_tree.py into Data/atlas_tree_poe1.json),
// allocation state, path finding and build persistence.
//
// Pure data + graph logic; no ImGui / GL. Rendering lives in atlas_view.cpp.
#pragma once

#include <string>
#include <vector>

// Where a sprite lives: sheet slot + normalized uv + world-unit quad size.
struct AtlasSpriteRef {
	int sheet = 0;
	float uv[4] = { 0, 0, 1, 1 };   // u0, v0, u1, v1
	float w = 0, h = 0;             // world units (sprite px at zoom 0.5 * 2)
};

// kind values (shared with tools/gen_atlas_tree.py)
enum : int {
	kAtlasNormal = 0,
	kAtlasNotable = 1,
	kAtlasKeystone = 2,
	kAtlasStart = 3,     // the single start node: always allocated, zero cost
	kAtlasWormhole = 4,  // gateway pair; teleport edge is a normal graph edge
};

struct AtlasNode {
	int id = 0;                       // GGG skill id (stable across data updates)
	std::string name;
	std::vector<std::string> stats;
	float x = 0, y = 0;               // world coords (precomputed by the generator)
	int kind = kAtlasNormal;
	AtlasSpriteRef on, off;           // allocated / unallocated icon
	std::vector<int> adj;             // neighbor node indices
	bool alloc = false;
};

struct AtlasEdge {
	int a = 0, b = 0;
	bool wormhole = false;            // paired-gateway edge: skip line drawing
	bool hasArc = false;              // same group+orbit: draw on the orbit circle
	float cx = 0, cy = 0, r = 0;      // arc circle (world)
	float a0 = 0, sweep = 0;          // ImGui PathArcTo angles: a0 .. a0+sweep
};

struct AtlasSheet { std::string file; int w = 0, h = 0; };

// off = unallocated, path = hover/can-allocate preview, on = allocated.
struct AtlasFrame { AtlasSpriteRef off, path, on; };

// Decorative sprite (mastery group icon / group background); never interactive.
struct AtlasDeco {
	std::string name;
	float x = 0, y = 0;
	AtlasSpriteRef spr;
	bool half = false;                // group bg stored as top half; mirror below
};

class AtlasTreeData {
public:
	// Reads Data/atlas_tree_poe1.json under exeDir. On failure returns false
	// and fills *err (UTF-8) when provided.
	bool Load(const std::wstring& exeDir, std::string* err);

	int UsedPoints() const;                       // allocated, excluding the start node
	int TotalPoints() const { return totalPoints_; }

	// Multi-source BFS from every allocated node through unallocated ones.
	// Returns the nodes to newly allocate, in order towards target (empty if
	// target is invalid, already allocated, or unreachable).
	std::vector<int> FindPathTo(int target) const;

	// Nodes that would be lost when deallocating idx: idx plus every allocated
	// node no longer reachable from the start node. Empty for the start node.
	std::vector<int> FindRemoveSet(int idx) const;

	void Alloc(const std::vector<int>& path);
	void Remove(const std::vector<int>& removeSet);
	void Reset();                                 // back to start-only

	// Reset + mark by GGG skill id + repair connectivity. Unknown ids are
	// silently dropped; returns how many ids actually mapped to nodes.
	int ApplyAllocIds(const std::vector<int>& ids);
	std::vector<int> AllocIds() const;            // allocated ids, start excluded
	const std::string& Version() const { return version_; }

	// Build persistence under exeDir\PobTools\atlas_build_poe1.json (multi-build
	// schema, see atlas_persist.h). SaveBuild updates only the active project;
	// LoadBuild applies the active project's ids via ApplyAllocIds.
	bool LoadBuild(const std::wstring& exeDir);
	bool SaveBuild(const std::wstring& exeDir) const;

	std::vector<AtlasNode> nodes;
	std::vector<AtlasEdge> edges;
	std::vector<AtlasSheet> sheets;
	AtlasFrame frames[5];                         // indexed by kind
	std::vector<AtlasDeco> masteries;
	std::vector<AtlasDeco> groupBg;
	AtlasSpriteRef bg;                            // full-tree background art
	bool hasBg = false;
	int root = -1;                                // index of the start node
	float minX = 0, minY = 0, maxX = 0, maxY = 0; // world bounds

private:
	// Keeps only allocated nodes reachable from the start node.
	void repairConnectivity();

	int totalPoints_ = 0;
	std::string version_;
};

// Headless logic check driven by "pob-zh.exe --atlas-selftest": loads the tree,
// runs allocation/removal scenarios, prints a report (attached console +
// atlas_selftest.txt next to the exe) and returns 0 on full pass.
int RunAtlasSelfTest(const std::wstring& exeDir);
