// PobTools passive-tree data model for the Timeless Jewel calculator's tree
// view: the condensed PoE1 character passive tree (generated by
// tools/gen_passive_tree.py into Data/passive_tree_poe1.json).
//
// Pure data + geometry; no ImGui / GL. Rendering lives in passive_tree_view.cpp.
// The sprite SHEETS are NOT bundled — they are read at runtime from the user's
// PoB folder (PathOfBuildingCommunity/TreeData/<treeVersion>/), like the .bin
// lookup tables. This file only carries geometry + normalized sprite uv.
#pragma once

#include <string>
#include <vector>

// kind values (shared with tools/gen_passive_tree.py)
enum : int {
	kPtNormal = 0,
	kPtNotable = 1,
	kPtKeystone = 2,
	kPtSocket = 3,
};

// Where a sprite lives: sheet slot + normalized uv + world-unit quad size.
struct PtSprite {
	int sheet = 0;
	float uv[4] = { 0, 0, 1, 1 };
	float w = 0, h = 0;
	bool valid = false;
};

struct PtNode {
	int id = 0;                          // GGG skill id
	std::string name, nameZh;
	int kind = kPtNormal;
	float x = 0, y = 0;                  // world coords (precomputed)
	std::vector<std::string> stats, statsZh;
	PtSprite on, off;                    // allocated / unallocated icon (sockets: none)
	std::vector<int> adj;                // neighbour node indices
};

struct PtEdge {
	int a = 0, b = 0;
	bool hasArc = false;                 // same group+orbit: draw on the orbit circle
	float cx = 0, cy = 0, r = 0;
	float a0 = 0, sweep = 0;             // ImGui PathArcTo angles
};

struct PtSheet { std::string file; int w = 0, h = 0; };
struct PtFrame { PtSprite off, path, on; };

// Decorative sprite (mastery icon / group background); never interactive.
struct PtDeco {
	std::string name;
	float x = 0, y = 0;
	PtSprite spr;
	bool half = false;                   // group bg stored as top half; mirror below
};

class PassiveTreeData {
public:
	// Reads Data/passive_tree_poe1.json under exeDir. On failure returns false
	// and fills *err (UTF-8) when provided.
	bool Load(const std::wstring& exeDir, std::string* err);

	// Node indices within `radiusWorld` of the socket node (POB rule: exclude the
	// socket itself, other sockets and masteries; membership is dist² <= r²).
	std::vector<int> NodesInRadius(int socketNodeIdx, float radiusWorld) const;

	// Find the node index for a GGG skill id, or -1.
	int IndexOfId(int id) const;

	const std::string& TreeVersion() const { return treeVersion_; }
	const std::string& Version() const { return version_; }

	std::vector<PtNode> nodes;
	std::vector<PtEdge> edges;
	std::vector<PtSheet> sheets;
	std::vector<int> sockets;            // node indices that are jewel sockets
	PtFrame frames[3];                   // indexed by kind (normal/notable/keystone)
	std::vector<PtDeco> masteries, groupbg;
	float minX = 0, minY = 0, maxX = 0, maxY = 0;

private:
	std::string treeVersion_;            // e.g. "3_28" (sheet subfolder)
	std::string version_;
};

// Headless check driven by "pob-zh.exe --passive-tree-selftest".
int RunPassiveTreeSelfTest(const std::wstring& exeDir);
