// The Lucide icon subset as a font, shared by every window that draws icons:
// the launcher, the standalone tool windows and --panel-selftest. One copy of
// the TTF bytes (host/data/icons_lucide.inc, generated by
// tools/gen_lucide_icons.py) and one rule for placing it on a text line.
#pragma once

#include <vector>

struct ImFont;
struct ImFontAtlas;
struct ImFontConfig;

namespace PobIcon {

// Raw TTF bytes, NOT compressed: the launcher builds its atlas on two threads at
// once, and ImGui's stb_decompress keeps its state in file-scope globals.
// Read-only and static, so every atlas can point at it without a keep-alive.
const unsigned char* FontData();
unsigned FontSize();

// The glyph range the icon font is merged over (kRangeFirst..kRangeLast, 0).
const unsigned short* GlyphRanges();

// The primary face's ascent as a fraction of its line height, read from 'hhea'
// the way stb_truetype scales it (ascent / (ascent - descent)). 0.8 when the
// table cannot be read.
float HheaAscentRatio(const std::vector<unsigned char>& ttf);

// Merges the icon font into the face that was added last, at `px`.
// `mergeCfg` is the caller's merge-mode config (FontDataOwnedByAtlas = false,
// MergeMode = true). Lucide's em box is all ascent and the glyphs fill ~4%..96%
// of it: placed as is, an icon would stand on the baseline and poke above the
// line, so it is shifted to centre its box on the text line. Call it LAST for a
// face, so a text font that uses the same Private Use Area keeps its glyphs.
void MergeInto(ImFontAtlas* atlas, float px, const ImFontConfig& mergeCfg, float primaryAscent);

// True when `face` can draw the icons (asked of the built atlas, never assumed).
bool FaceHasIcons(const ImFont* face);

} // namespace PobIcon
