// Generated by tools/gen_lucide_icons.py -- do not edit by hand.
//
// Icon glyphs for the launcher (Lucide 1.47.0, ISC; see host/data/icons_lucide.inc).
// Each constant is the icon's UTF-8 string: draw it with the body / small / title
// face (the icon font is merged into them) or through PobUi::Icon. They are NOT
// in the launcher string table on purpose: the glyphs are Private Use Area
// codepoints that no text font has, and the coverage selftest must not ask for them.
#pragma once

namespace PobIcon {

inline constexpr const char Zap[] = "\xee\x86\xb4"; // zap U+E1B4
inline constexpr const char Refresh[] = "\xee\x85\x85"; // refresh-cw U+E145
inline constexpr const char Download[] = "\xee\x82\xb2"; // download U+E0B2
inline constexpr const char House[] = "\xee\x83\xb5"; // house U+E0F5
inline constexpr const char Funnel[] = "\xee\x83\x9c"; // funnel U+E0DC
inline constexpr const char Crosshair[] = "\xee\x82\xac"; // crosshair U+E0AC
inline constexpr const char Gem[] = "\xee\x89\x82"; // gem U+E242
inline constexpr const char CodeXml[] = "\xee\x88\x86"; // code-xml U+E206
inline constexpr const char ChartColumn[] = "\xee\x8a\xa3"; // chart-column U+E2A3
inline constexpr const char Languages[] = "\xee\x83\xbe"; // languages U+E0FE
inline constexpr const char AlignLeft[] = "\xee\x86\x85"; // text-align-start U+E185
inline constexpr const char AppWindow[] = "\xee\x90\xa6"; // app-window U+E426
inline constexpr const char Globe[] = "\xee\x83\xa8"; // globe U+E0E8
inline constexpr const char TrendingUp[] = "\xee\x86\x91"; // trending-up U+E191
inline constexpr const char Link[] = "\xee\x84\x82"; // link U+E102
inline constexpr const char Folder[] = "\xee\x83\x97"; // folder U+E0D7
inline constexpr const char FileText[] = "\xee\x83\x8c"; // file-text U+E0CC
inline constexpr const char FolderOpen[] = "\xee\x89\x87"; // folder-open U+E247
inline constexpr const char X[] = "\xee\x86\xb2"; // x U+E1B2
inline constexpr const char Info[] = "\xee\x83\xb9"; // info U+E0F9
inline constexpr const char CircleAlert[] = "\xee\x81\xb7"; // circle-alert U+E077
inline constexpr const char TriangleAlert[] = "\xee\x86\x93"; // triangle-alert U+E193
inline constexpr const char CircleX[] = "\xee\x82\x84"; // circle-x U+E084
inline constexpr const char CircleCheck[] = "\xee\x88\xa6"; // circle-check U+E226
inline constexpr const char Check[] = "\xee\x81\xac"; // check U+E06C
inline constexpr const char ChevronDown[] = "\xee\x81\xad"; // chevron-down U+E06D
inline constexpr const char ChevronRight[] = "\xee\x81\xaf"; // chevron-right U+E06F
inline constexpr const char Search[] = "\xee\x85\x91"; // search U+E151
inline constexpr const char Plus[] = "\xee\x84\xbd"; // plus U+E13D
inline constexpr const char ExternalLink[] = "\xee\x82\xb9"; // external-link U+E0B9
inline constexpr const char Copy[] = "\xee\x82\x9e"; // copy U+E09E
inline constexpr const char Image[] = "\xee\x83\xb6"; // image U+E0F6
inline constexpr const char ImagePlus[] = "\xee\x87\xb7"; // image-plus U+E1F7
inline constexpr const char RotateCcw[] = "\xee\x85\x88"; // rotate-ccw U+E148
inline constexpr const char MessageCircle[] = "\xee\x84\x96"; // message-circle U+E116
inline constexpr const char Coffee[] = "\xee\x82\x96"; // coffee U+E096
inline constexpr const char Palette[] = "\xee\x87\x9d"; // palette U+E1DD
inline constexpr const char History[] = "\xee\x87\xb5"; // history U+E1F5
inline constexpr const char Undo[] = "\xee\x8a\xa1"; // undo-2 U+E2A1
inline constexpr const char Map[] = "\xee\x84\x90"; // map U+E110
inline constexpr const char Layers[] = "\xee\x94\xa9"; // layers U+E529
inline constexpr const char GitCompare[] = "\xee\x8d\x99"; // git-compare U+E359
inline constexpr const char Minimize[] = "\xee\x84\x9b"; // minimize-2 U+E11B
inline constexpr const char Share[] = "\xee\x85\x96"; // share-2 U+E156
inline constexpr const char MoreHorizontal[] = "\xee\x82\xb6"; // ellipsis U+E0B6
inline constexpr const char Trash[] = "\xee\x86\x8e"; // trash-2 U+E18E
inline constexpr const char Pencil[] = "\xee\x87\xb9"; // pencil U+E1F9
inline constexpr const char CopyPlus[] = "\xee\x8f\xbd"; // copy-plus U+E3FD
inline constexpr const char Upload[] = "\xee\x86\x9e"; // upload U+E19E
inline constexpr const char Compass[] = "\xee\x82\x9b"; // compass U+E09B
inline constexpr const char List[] = "\xee\x84\x86"; // list U+E106
inline constexpr const char StickyNote[] = "\xee\x8c\x83"; // sticky-note U+E303
inline constexpr const char Minus[] = "\xee\x84\x9c"; // minus U+E11C
inline constexpr const char Camera[] = "\xee\x81\xa4"; // camera U+E064
inline constexpr const char Eye[] = "\xee\x82\xba"; // eye U+E0BA
inline constexpr const char EyeOff[] = "\xee\x82\xbb"; // eye-off U+E0BB
inline constexpr const char Play[] = "\xee\x84\xbc"; // play U+E13C
inline constexpr const char Square[] = "\xee\x85\xa7"; // square U+E167
inline constexpr const char Volume[] = "\xee\x86\xab"; // volume-2 U+E1AB
inline constexpr const char Save[] = "\xee\x85\x8d"; // save U+E14D

// The one range the icon font is merged over (min..max of the codepoints above).
inline constexpr unsigned short kRangeFirst = 0xE064;
inline constexpr unsigned short kRangeLast  = 0xE529;
// For the selftest: one icon that must be in the atlas.
inline constexpr unsigned short kProbe = 0xE1B4; // zap
inline constexpr int kCount = 60;

} // namespace PobIcon
