// PobTools 發佈簽章公鑰 —— GENERATED by tools/gen_signing_keys.ps1，請勿手改。
//
// 每一把都是 ECDSA P-256 的未壓縮公鑰點 X||Y，共 64 bytes 寫成 128 個小寫十六
// 進位字元。私鑰在維護者的 %USERPROFILE%\.pobtools\ 底下，永遠不進這個 repo。
//
// 兩把的理由：primary 是平常發版用的；backup 平常不碰、離線保存，只在 primary
// 外洩或遺失時啟用。客戶端任一把驗過就算過，所以換用 backup 發版不需要使用者
// 做任何事。⚠ 兩把都遺失 = 所有已安裝的客戶端永久失去自動更新。
//
// ⚠ 改動這份清單就是改動信任根。加一把新的公鑰只對「之後才安裝的客戶端」生效；
// 已經在外面跑的 exe 認的永遠是它自己編進去的那兩把。
#pragma once

// index 0 = primary, index 1 = backup
static const char* const kUpdatePublicKeysHex[] = {
	"65519f45a6c78c8b22b6b68d3a6a25771a7ab2757a6a793a332cdbb1124c2d587bd1c45dac4813209e2ce131f8b546c3f59a23c263aac97fd51cb17fecedbf0d",
	"a5418ed1d3f8e1f734a2c2b9464c23096085141ed1c475e64d7dee40a1ac0a218fae5991382084e06a35f71c7b0c1802e20e93bc64dd6556f5cf9691cd1ff24c",
};
static const int kUpdatePublicKeyCount =
	(int)(sizeof(kUpdatePublicKeysHex) / sizeof(kUpdatePublicKeysHex[0]));
